In [2]:
import pandas as pd
import numpy as np

In [12]:
df = pd.read_csv("Australia data.csv")

In [15]:
df[(df["AreaName"]=="Europe") & (df["RegName"]=="Southern Europe")]

,OdName,CODE,AreaName,RegName,DevName,1980,1981,1982,1983,1984,...,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008
1,Albania,ALB,Europe,Southern Europe,Developed regions,0,0,0,0,0,...,70,110,110,200,250,140,130,110,110,140
4,Andorra,AND,Europe,Southern Europe,Developed regions,0,0,10,0,0,...,10,0,10,10,0,10,10,0,10,10
25,Bosnia and Herzegovina,BIH,Europe,Southern Europe,Developed regions,0,0,0,0,0,...,700,560,370,310,240,240,240,250,300,320
51,Croatia,HRV,Europe,Southern Europe,Developed regions,0,0,0,0,0,...,840,950,830,580,510,360,590,400,270,340
80,Gibraltar,GIB,Europe,Southern Europe,Developed regions,0,0,0,0,0,...,0,10,10,0,10,0,10,0,10,0
81,Greece,GRC,Europe,Southern Europe,Developed regions,4280,5040,3560,3210,4060,...,2780,2170,2010,2300,1880,1300,1380,1260,1190,1130
91,Holy See,VAT,Europe,Southern Europe,Developed regions,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
101,Italy,ITA,Europe,Southern Europe,Developed regions,4210,4310,2620,2200,2400,...,1560,1750,1890,1690,1810,2250,2250,2560,2590,2840
124,Malta,MLT,Europe,Southern Europe,Developed regions,1220,1850,880,610,660,...,210,190,170,230,250,290,250,250,230,250
159,Portugal,PRT,Europe,Southern Europe,Developed regions,550,1710,1630,1300,1320,...,230,190,230,290,320,360,350,320,340,390
179,Slovenia,SVN,Europe,Southern Europe,Developed regions,0,0,0,0,0,...,130,180,240,220,140,80,130,140,120,130
183,Spain,ESP,Europe,Southern Europe,Developed regions,930,1480,1460,690,600,...,530,650,690,790,750,1000,950,1010,1130,1400
194,The former Yugoslav Republic of Macedonia,MKD,Europe,Southern Europe,Developed regions,0,0,0,0,0,...,600,430,620,580,620,500,510,610,650,660

0       AFG
1       ALB
2       DZA
3       ASM
4       AND
       ...
217     WLF
218    ESH
219     YEM
220     ZMB
221     ZWE
Name: CODE, Length: 222, dtype: object